print('Note to Future Me')
print('7-30-23')
print('I am excited to get started with python.')
print('Hopefully, I will get comfortable with backend coding.')
print('How do things look in the future? Do I get things figured out with practice?')
print('💕 Jessica')